version: "2"
services:
  lms:
    image: moodlehq/moodle-php-apache:7.4
    restart: always
    ports:
      - ${MOODLE_DOCKER_WEB_PORT}:80
      - ${MOODLE_DOCKER_WEB_SSL_PORT}:443
    volumes:
      - ${MOODLE_DOCKER_MOODLE}:/var/www/html
      - ${MOODLE_DOCKER_MOODLEDATA}:/var/www/moodledata
      - ${APACHE_SSL}:/etc/ssl/moodle
      - ${APACHE_SSL_CONFIG}:/etc/apache2/sites-available/default-ssl.conf
      - ${PHP_INI}:/usr/local/etc/php/conf.d/docker-php-moodle.ini
    environment:
      MOODLE_DOCKER_DBHOSTNAME: "${MOODLE_DOCKER_DBHOSTNAME}"
      MOODLE_DOCKER_DBNAME: "${MOODLE_DOCKER_DBNAME}"
      MOODLE_DOCKER_DBUSER: "${MOODLE_DOCKER_DBUSER}"
      MOODLE_DOCKER_DBPASS: "${MOODLE_DOCKER_DBPASS}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}"
      MOODLE_DOCKER_WEB_SITETYPE: "${MOODLE_DOCKER_WEB_SITETYPE}"
    networks:
      - lms
volumes:
  lms-data:
networks:
  lms:
    driver: bridge